"""Added tool_call table

Revision ID: cf9eedbf9270
Revises: 169bed537507
Create Date: 2025-01-08 12:26:38.657298

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf9eedbf9270"
down_revision: Union[str, None] = "169bed537507"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tool_calls",
        sa.Column("tool_call_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("arguments", sa.String(), nullable=False),
        sa.Column("validated", sa.Boolean(), nullable=True),
        sa.Column("message_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.message_id"],
        ),
        sa.PrimaryKeyConstraint("tool_call_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tool_calls")
    # ### end Alembic commands ###
